version: "3.9"

services:
  devopsdb:
    image: nagaraju444/dbimage:v1
    ports:
      - "3306:3306"
    deploy:
      replicas: 2
    networks:
      - mynetwork
  vpromq01:
    image: rabbitmq:3-management
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: nagaraju444/appimage:v1
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
